// All 10 core patterns — metadata only, card data lazy-loaded per pattern
export const PATTERNS = [
  {
    id: 'sliding-window',
    name: 'Arrays & sliding window',
    slug: 'sliding-window',
    color: '#1A56B0',
    bgColor: '#E8F0FB',
    signalPhrases: ['contiguous subarray', 'max/min in window', 'at most k', 'fixed window size'],
    skeletonCode: [
      'int left = 0;',
      'for (int right = 0; right < n; right++) {',
      '    // expand: process nums[right]',
      '    while (conditionViolated) {',
      '        // shrink: process nums[left], left++',
      '    }',
      '    // update answer',
      '}',
    ],
  },
  {
    id: 'two-pointers',
    name: 'Two pointers & fast/slow',
    slug: 'two-pointers',
    color: '#1A7A4A',
    bgColor: '#E1F5EE',
    signalPhrases: ['sorted array', 'pair with sum', 'palindrome', 'cycle detection', 'remove duplicates'],
    skeletonCode: [
      'int left = 0, right = nums.length - 1;',
      'while (left < right) {',
      '    if (condition) {',
      '        // process or shrink',
      '        left++;',
      '    } else {',
      '        right--;',
      '    }',
      '}',
    ],
  },
  {
    id: 'trees-graphs',
    name: 'Trees & graphs (BFS/DFS)',
    slug: 'trees-graphs',
    color: '#6B3FA0',
    bgColor: '#F3EEF9',
    signalPhrases: ['level order', 'shortest path', 'connected components', 'tree traversal', 'number of islands'],
    skeletonCode: [
      '// BFS',
      'Queue<Integer> queue = new LinkedList<>();',
      'queue.offer(start);',
      'while (!queue.isEmpty()) {',
      '    int node = queue.poll();',
      '    for (int neighbor : graph.get(node)) {',
      '        if (!visited.contains(neighbor)) {',
      '            visited.add(neighbor);',
      '            queue.offer(neighbor);',
      '        }',
      '    }',
      '}',
    ],
  },
  {
    id: 'dynamic-programming',
    name: 'Dynamic programming',
    slug: 'dynamic-programming',
    color: '#854F0B',
    bgColor: '#FEF9E7',
    signalPhrases: ['max/min ways', 'count combinations', 'optimal substructure', 'overlapping subproblems', 'can you reach'],
    skeletonCode: [
      'int[] dp = new int[n + 1];',
      'dp[0] = baseCase;',
      'for (int i = 1; i <= n; i++) {',
      '    dp[i] = /* transition from dp[i-1], dp[i-2], ... */;',
      '}',
      'return dp[n];',
    ],
  },
  {
    id: 'linked-lists',
    name: 'Linked lists',
    slug: 'linked-lists',
    color: '#A0295A',
    bgColor: '#FDE8F0',
    signalPhrases: ['reverse linked list', 'detect cycle', 'merge lists', 'find middle', 'nth from end'],
    skeletonCode: [
      'ListNode prev = null, curr = head;',
      'while (curr != null) {',
      '    ListNode next = curr.next;',
      '    curr.next = prev;',
      '    prev = curr;',
      '    curr = next;',
      '}',
      'return prev;',
    ],
  },
  {
    id: 'binary-search',
    name: 'Binary search',
    slug: 'binary-search',
    color: '#0C447C',
    bgColor: '#E6F1FB',
    signalPhrases: ['sorted array', 'find target', 'minimum in rotated', 'search range', 'first/last position'],
    skeletonCode: [
      'int left = 0, right = nums.length - 1;',
      'while (left <= right) {',
      '    int mid = left + (right - left) / 2;',
      '    if (nums[mid] == target) return mid;',
      '    else if (nums[mid] < target) left = mid + 1;',
      '    else right = mid - 1;',
      '}',
      'return -1;',
    ],
  },
  {
    id: 'backtracking',
    name: 'Backtracking',
    slug: 'backtracking',
    color: '#712B13',
    bgColor: '#FAECE7',
    signalPhrases: ['all combinations', 'all permutations', 'generate all subsets', 'word search', 'N-queens'],
    skeletonCode: [
      'void backtrack(List<List<Integer>> result, List<Integer> current, int start) {',
      '    result.add(new ArrayList<>(current)); // or: if valid, add',
      '    for (int i = start; i < nums.length; i++) {',
      '        current.add(nums[i]);          // choose',
      '        backtrack(result, current, i + 1); // explore',
      '        current.remove(current.size() - 1); // unchoose',
      '    }',
      '}',
    ],
  },
  {
    id: 'heap-priority-queue',
    name: 'Heap / priority queue',
    slug: 'heap-priority-queue',
    color: '#085041',
    bgColor: '#E1F5EE',
    signalPhrases: ['top K elements', 'K largest', 'K smallest', 'median stream', 'merge K sorted'],
    skeletonCode: [
      '// Min-heap for top K largest',
      'PriorityQueue<Integer> heap = new PriorityQueue<>();',
      'for (int num : nums) {',
      '    heap.offer(num);',
      '    if (heap.size() > k) heap.poll(); // evict smallest',
      '}',
      'return heap.peek(); // Kth largest',
    ],
  },
  {
    id: 'stack-monotonic',
    name: 'Stack & monotonic stack',
    slug: 'stack-monotonic',
    color: '#3C3489',
    bgColor: '#EEEDFE',
    signalPhrases: ['next greater element', 'valid parentheses', 'largest rectangle', 'daily temperatures', 'monotonic'],
    skeletonCode: [
      'Deque<Integer> stack = new ArrayDeque<>();',
      'for (int i = 0; i < nums.length; i++) {',
      '    while (!stack.isEmpty() && nums[stack.peek()] < nums[i]) {',
      '        int idx = stack.pop();',
      '        // process: nums[i] is next greater for idx',
      '    }',
      '    stack.push(i);',
      '}',
    ],
  },
  {
    id: 'string-manipulation',
    name: 'String manipulation',
    slug: 'string-manipulation',
    color: '#444441',
    bgColor: '#F5F5F5',
    signalPhrases: ['anagram', 'palindrome', 'longest common', 'string matching', 'encode decode'],
    skeletonCode: [
      'Map<Character, Integer> freq = new HashMap<>();',
      'for (char c : s.toCharArray()) {',
      '    freq.merge(c, 1, Integer::sum);',
      '}',
      '// check / compare freq maps',
    ],
  },
]

export const PATTERN_MAP = Object.fromEntries(PATTERNS.map(p => [p.id, p]))

export const CONCEPT_TAGS = [
  'hashmap', 'prefix-sum', 'two-pass', 'in-place', 'memoization',
  'tabulation', 'cycle-detection', 'topological-sort', 'divide-and-conquer',
  'monotonic-invariant', 'frequency-count', 'bit-manipulation',
]
